routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('animes','AnimeController');
Route::resource('genres','GenreController');

app/Anime.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Anime extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AnimeController.php
<?php

namespace App\Http\Controllers;

use App\Anime;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use DB;
use App;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests\CreateOrEditAnimeRequest;

class AnimeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $animes = DB::table('animes')
            ->orderBy('title')
            ->paginate(20);
        
        return view('anime.anime-index')
            ->with('animes',$animes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('anime.anime-create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\CreateOrEditAnimeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateOrEditAnimeRequest $request)
    {
        $anime = new Anime();
        $anime->title = $request->input('title');
        $anime->episode_count = $request->input('episode-count');
        $anime->episode_duration = $request->input('episode-duration');
        $anime->start_date = $request->input('start-date');
        $anime->finish_date = $request->input('finish-date');
        $anime->description = nl2br($request->input('description'));
        $anime->save();

        return redirect('animes');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Anime  $anime
     * @return \Illuminate\Http\Response
     */
    public function show(Anime $anime)
    {
        return view('anime.anime-show')
            ->with('anime',$anime);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Anime  $anime
     * @return \Illuminate\Http\Response
     */
    public function edit(Anime $anime)
    {
        return view('anime.anime-edit')
            ->with('anime',$anime);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\CreateOrEditAnimeRequest  $request
     * @param  \App\Anime  $anime
     * @return \Illuminate\Http\Response
     */
    public function update(CreateOrEditAnimeRequest $request, Anime $anime)
    {
        $anime->title = $request->input('title');
        $anime->episode_count = $request->input('episode-count');
        $anime->episode_duration = $request->input('episode-duration');
        $anime->start_date = $request->input('start-date');
        $anime->finish_date = $request->input('finish-date');
        $anime->description = nl2br($request->input('description'));
        $anime->save();

        return redirect('animes');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Anime  $anime
     * @return \Illuminate\Http\Response
     */
    public function destroy(Anime $anime)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/anime/anime-create.blade.php
@extends('layouts.master')

@section('title', 'Anime index')

@section('content')
    <h2> @lang('anime.create_new_anime') </h2>
	
	<a href="/animes">@lang('navigation.back')</a>
	<div>
		@include('partials.errors')
		<form id="form-anime" method="POST" enctype="multipart/form-data" action="/animes/">
	    	@include('anime.anime-form')
		</form>
	</div>
@endsection

@section('footerScripts')
    @parent
@endsection

resources/views/anime/anime-edit.blade.php
@extends('layouts.master')

@section('title', 'Anime index')

@section('content')
    <h2> @lang('anime.edit_anime') </h2>
	
	<a href="/animes">@lang('navigation.back')</a>
	<div>
		@include('partials.errors')
		<form id="form-anime" method="POST" enctype="multipart/form-data" action="/animes/{{$anime->id}}">
			<input type="hidden" name="_method" value="PATCH">
	    	@include('anime.anime-form')
		</form>
	</div>
@endsection

@section('footerScripts')
    @parent
@endsection

resources/views/anime/anime-form.blade.php
{{ csrf_field() }}
@lang('anime.title'):<input value="{{ $anime->title or old('title') }}" type="text" name="title" placeholder=@lang('anime.title')>
<br>
@lang('anime.episode_count'): <input value="{{ $anime->episode_count or old('episode-count') }}" type="integer" name="episode-count" placeholder=@lang('anime.episode_count')> 
<br>
@lang('anime.episode_duration'): <input value="{{ $anime->episode_duration or old('episode-duration') }}" type="integer" name="episode-duration" placeholder=@lang('anime.episode_duration')> 
<br>
@lang('anime.start_date'): <input value="{{ $anime->start_date or old('start-date') }}" type="date" name="start-date" placeholder=@lang('anime.start_date')> 
<br>
@lang('anime.finish_date'): <input value="{{ $anime->finish_date or old('finish-date') }}" type="date" name="finish-date" placeholder=@lang('anime.finish_date')> 
<br>
@lang('anime.description'):<textarea name="description" form="form-anime" placeholder=@lang('anime.description')>{{ $anime->description or old('description') }}</textarea>
<br>
<input type="submit">

resources/views/anime/anime-index.blade.php
@extends('layouts.master')

@section('title', 'Anime index')

@section('content')
    <h2> @lang('anime.anime_list') </h2>
	
	<a href="/">@lang('navigation.back')</a>
	<br>
    @include('partials.errors')
    <br>
    <a href="{{ route('animes.create') }}">@lang('anime.create_new_anime')</a>
    <ul>
		@forelse ($animes as $anime)
			<li> 
				<b>{{ $loop->iteration }}.</b> <a href="{{ URL('animes/'.$anime->id) }}">{{ $anime->title }}</a>
				<ul>
					<li> 
						<a href="{{ route('animes.edit', [$anime->id]) }}">@lang('anime.edit_anime')</a>
					</li>
				</ul>
			</li>
		@empty
			No anime stored yet.
		@endforelse
	</ul>

	{{ $animes->links() }}
@endsection

@section('footerScripts')
    @parent
@endsection

resources/views/anime/anime-show.blade.php
@extends('layouts.master')

@section('title', 'Anime show')

@section('content')
    <h2> {{ $anime->title }} </h2>
	
	<a href="/animes"> @lang('navigation.back')</a>
    @include('partials.errors')
	<ul>
		<li> <b> @lang('anime.episode_count'): </b> {{ $anime->episode_count or trans('anime.unknown') }}
		<li> <b> @lang('anime.episode_duration'): </b> {{ $anime->episode_duration or trans('anime.unknown') }}
			@if ($anime->episode_duration)
				 minutes					
			@endif 
		<li> <b> @lang('anime.aired_period'): </b> {{ $anime->start_date or trans('anime.unknown') }} to {{ $anime->finish_date or trans('anime.unknown') }}
		<li> <b> @lang('anime.description'): </b> {{ $anime->description or trans('anime.unknown') }}

	</ul>
@endsection

@section('footerScripts')
    @parent
@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('title', 'Dashboard')

@section('content')
    
    Welcome to your application dashboard!
    <div class="content" data-page-name="Dashboard">
        <p>Here's why you should sign up for our app: <strong>It's Great.</strong></p>
        @include('sign-up-button', ['text' => 'See just how great it is', 'pageName' => 'Dashboard'])
        <br>
        <a href="<?php echo route('animes.index'); ?>"> Anime </a>
    </div>
@endsection

@section('footerScripts')
    @parent
    <script src="dashboard.js"></script>
@endsection

resources/views/layouts/master.blade.php
<html>
	<head>
		<title>Just Another Anime List | @yield('title', 'Home Page')</title>
	</head>
	<body>
		@include('partials.sidebar')
		<div class="container">
		@yield('content')
		</div>
		@section('footerScripts')
			<script src="app.js"></script>
		@show
	</body>
</html>

resources/views/partials/empty-module.blade.php
<div class="sidebar-module">
	No modules :(
</div>

resources/views/partials/errors.blade.php
@if ($errors->any())
	<div class="alert alert-danger">
		<ul>
			@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

resources/views/partials/module.blade.php
<div class="sidebar-module">
	<h1>{{ $module->title }}</h1>
</div>

resources/views/partials/sidebar.blade.php
<div class="sidebar">
	@each('partials.module', $posts, 'module', 'partials.empty-module')
</div>

resources/views/sidebar.blade.php
<div class="sidebar">
	@each('partials.module', $posts, 'module', 'partials.empty-module')
</div>

resources/views/sign-up-button.blade.php
<a class="button button--callout" data-page-name="{{ $pageName }}">
	<i class="exclamation-icon"></i> {{ $text }}
</a>